import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import Card from "../components/Card";
import coffeeShopsData from "../data/coffee-shops.json";
import cls from "classnames";

export async function getStaticProps(context) {
  return {
    props: {
      coffeeShops: coffeeShopsData,
    }, // will be passed to the page component as props
  };
}

export default function Home({ coffeeShops }) {
  const handleOnButtonClick = () => {};

  return (
    <>
      <Head>
        <title>Coffee Meister</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bgGlass">
        <main className={styles.main}>
          <div className={styles.description}>
            <Banner
              buttonText={"View shops nearby"}
              handleOnClick={handleOnButtonClick}
            />
          </div>
          {coffeeShops.length > 0 ? (
            <>
              <h2 className={styles.heading2}>Atlanta Coffee Shops</h2>
              <div className={styles.cardLayout}>
                {coffeeShops.map((shops) => {
                  return (
                    <Card
                      key={shops.id}
                      href={`/coffee-shop/${shops.id}`}
                      name={shops.name}
                      imgUrl={shops.imgUrl}
                      className={styles.card}
                    />
                  );
                })}
              </div>
            </>
          ) : (
            <h2 className={styles.heading2}>Loading...</h2>
          )}
        </main>
      </div>
    </>
  );
}
