import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import Card from "../components/Card";
import coffeeStores from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores,
    }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  const handleOnButtonClick = () => {};

  return (
    <>
      <Head>
        <title>Coffee Meister</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <Banner
            buttonText={"View stores nearby"}
            handleOnClick={handleOnButtonClick}
          />
        </div>
        {props.coffeeStores.length > 0 ? (
          <>
            <h2 className={styles.heading2}>Atlanta Coffee Shops</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((stores) => {
                return (
                  <Card
                    key={stores.id}
                    href={`/coffee-store/${stores.id}`}
                    name={stores.name}
                    imgUrl={stores.imgUrl}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        ) : (
          <h2 className={styles.heading2}>Loading...</h2>
        )}
      </main>
    </>
  );
}
